import torch
x = torch.tensor([1, 2, 2, 2, 2, 2, 2])

In [8]:
import torch

x = torch.tensor([1, 2, 2, 2, 2, 2, 2, 2])

if torch.cuda.is_available():
    device = torch.device("cuda")           # GPU
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
tensor([2., 3., 3., 3., 3., 3., 3., 3.], dtype=torch.float64)


In [16]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [17]:
out.backward()
print(x.grad)

out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[6.5000, 6.5000],
        [6.5000, 6.5000]])
