导入 pytorch 库

In [12]:
import torch

生成张量矩阵

In [28]:
height = 4
width = 5
type = torch.float
x = torch.zeros(height, width, dtype = type)
x = torch.rand(height, width)
print(x.new_ones(height, width))
print(torch.randn_like(x, dtype = torch.float))
print(x.size(), x.shape)        # 返回 height, width

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0.0547,  0.5870, -0.5169, -1.3087, -0.7692],
        [ 0.4217,  0.1433, -1.5285, -0.1153, -0.0694],
        [-1.9810, -1.5888, -0.7454, -0.6610, -1.0191],
        [ 2.1525,  0.4409,  0.3594, -1.9272,  1.5251]])
torch.Size([4, 5]) torch.Size([4, 5])


利用 view 函数重塑张量

In [29]:
print(x.view(20))
print(x.view(2, 10))

tensor([0.5915, 0.8367, 0.9751, 0.4737, 0.1089, 0.5773, 0.0857, 0.8377, 0.7627,
        0.7098, 0.1919, 0.6099, 0.2173, 0.6880, 0.1656, 0.7736, 0.1788, 0.1442,
        0.7041, 0.6251])
tensor([[0.5915, 0.8367, 0.9751, 0.4737, 0.1089, 0.5773, 0.0857, 0.8377, 0.7627,
         0.7098],
        [0.1919, 0.6099, 0.2173, 0.6880, 0.1656, 0.7736, 0.1788, 0.1442, 0.7041,
         0.6251]])


ndarray 和 tensor 相互转化

In [ ]:
torch.from_numpy(tensor)    # tensor 转 ndarray